name: Govee to MQTT Bridge
image: ghcr.io/sitapix/govee2mqtt
version: "2025.11.25-60a39bcc"
slug: govee2mqtt-lite
description: Control Govee Devices
url: https://github.com/sitapix/govee2mqtt
breaking_versions:
  - "2025.11.25-60a39bcc"
arch:
  - amd64
  - aarch64
init: false
boot: auto
startup: services
services:
  - mqtt:need

apparmor: true

ingress: true
ingress_port: 8056

# Host network access is required for LAN discovery
host_network: true

map:
  - type: addon_config
    read_only: false
    path: /config

options:
  temperature_scale: "C"

schema:
  temperature_scale: "str?"
  govee_email: "str?"
  govee_password: "password?"
  govee_api_key: "password?"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_username: "str?"
  mqtt_password: "password?"
  debug_level: "str?"
  no_multicast: "bool?"
  broadcast_all: "bool?"
  global_broadcast: "bool?"
  scan: "str?"
  disable_effects: "bool?"
  allowed_effects: "str?"
